name: Testing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            toxenv: py310
          - python-version: "3.14"
            toxenv: py314
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: Install dependencies
        run: pip install tox
      - name: Validate project configuration
        run: tox
        env:
          TOXENV: validate
      - name: Run linting and formatting
        run: tox
        env:
          TOXENV: lint
      - name: Run type checking
        run: |
            tox
        env:
          TOXENV: type
      - name: Run tests
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
